@startuml 
skinparam shadowing false
skinparam BackgroundColor hidden
start 
repeat 
:revoir opération système; 
note right: p.ex. <i>créerNouvelleVente()</i>
:déterminer contrôleur; 
note right: appliquer GRASP Contrôleur\n(voir les détails au livre) 
:rappeler le contrat; 
note right: les postconditions, p.ex.,\n-Une instance <i>v</i> de Vente a été créée\n-<i>v</i> a été associée au Registre\n-Des attributs de <i>v</i> ont été initialisés 
repeat 
:concevoir (raffiner) un diagramme d'interaction\nde l'opération système satisfaisant toutes\nles postconditions du contrat d'opération et\nretournant l'information du message de retour\nle cas échéant; 
note right: voir le chapitre F15/A16 
repeat while (reste des postconditions insatisfaites\nou infos pas encore retournées) 
repeat while (reste des opérations système) 
stop 
@enduml